api_clash/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('card/', include(('cards.urls', 'cards'), namespace='card')),
    path(
        'location/',
        include(('locations.urls', 'locations'), namespace='location')
        ),
    path('player/', include(('players.urls', 'players'), namespace='player')),
    path('clan/', include(('clans.urls', 'clans'), namespace='clan')),
]

cards/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.card_list, name='card_list'),
    path('list_with_react/', views.card_list_with_react, name='card_list'),
    path('list_with_vue/', views.card_list_with_vue, name='card_list'),
]

players/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('<playertag>/detail/', views.player_detail, name='player_detail'),
    path('<playertag>/chests/', views.player_chests, name='player_chests'),
    path('<playertag>/battlelog/', views.player_battles, name='player_battles'),
]

players/models.py
from django.db import models

# Create your models here.

players/views.py
import requests

from django.shortcuts import render
from django.conf import settings

from credential.views import get_headers

# Create your views here.


def player_detail(request, playertag):
    import urllib.parse
    playertag = urllib.parse.quote_plus(playertag)
    url = '%splayers/%s' % (settings.BASE_URL, playertag)
    headers = get_headers()

    response = requests.get(
        url=url,
        headers=headers,
    )

    if response.status_code == 200:
        response = response.json()
    else:
        response = {}

    return render(request, 'player/detail.html', {'player': response})


def player_chests(request, playertag):
    import urllib.parse
    playertag = urllib.parse.quote_plus(playertag)
    url = '%splayers/%s/upcomingchests' % (settings.BASE_URL, playertag)
    headers = get_headers()

    response = requests.get(
        url=url,
        headers=headers,
    )

    if response.status_code == 200:
        response = response.json()['items']
    else:
        response = {}

    return render(request, 'player/chests.html', {'chests': response})


def player_battles(request, playertag):
    import urllib.parse
    playertag = urllib.parse.quote_plus(playertag)
    url = '%splayers/%s/battlelog' % (settings.BASE_URL, playertag)
    headers = get_headers()

    response = requests.get(
        url=url,
        headers=headers,
    )

    if response.status_code == 200:
        response = response.json()
    else:
        response = {}

    return render(request, 'player/battlelog.html', {'battles': response})

players/templates/player/battlelog.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
            {% for item in battles %}
                <div class="row">
                    <table class="table table-borderless table-sm">
                        <tr>
                            <th>Type:</th>
                            <td>{{ item.type }}</td>
                            <th>Arena:</th>
                            <td>{{ item.arena.name }}</td>
                            <th>Game Mode:</th>
                            <td>{{ item.gameMode.name }}</td>
                            <th>Deck Selection:</th>
                            <td>{{ item.deckSelection }}</td>
                        </tr>
                    </table>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {% for team in item.team %}
                            {{ team.name }} <i class="text-muted">[{{ team.clan.name }}]</i>
                            | startingTrophies: {{ team.startingTrophies }}
                            | trophyChange: {{ team.trophyChange }}
                            | crowns: {{ team.crowns }}
                            <div class="row no-gutters">
                                {% for card in team.cards %}
                                    <div class="col-md-1">
                                        <div class="card text-center">
                                            <img src="{{ card.iconUrls.medium }}" alt="{{ card.name }}" height="70px" class="rounded">
                                            <i class="text-muted" style="font-size: 12px">Lvl: {{ card.level }}</i>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-6">
                        {% for team in item.opponent %}
                            {{ team.name }} <i class="text-muted">[{{ team.clan.name }}]</i>
                            | startingTrophies: {{ team.startingTrophies }}
                            | trophyChange: {{ team.trophyChange }}
                            | crowns: {{ team.crowns }}
                            <div class="row no-gutters">
                                {% for card in team.cards %}
                                    <div class="col-md-1">
                                        <div class="card text-center">
                                            <img src="{{ card.iconUrls.medium }}" alt="{{ card.name }}" height="70px" class="rounded">
                                            <i class="text-muted" style="font-size: 12px">Lvl: {{ card.level }}</i>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <hr/>
            {% endfor %}
        </div>
    </div>
{% endblock %}

players/templates/player/chests.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-8">
            <table class="table table-light table-sm table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>Index</th>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in chests %}
                        <tr>
                            <td>{{ item.index }}</td>
                            <td>{{ item.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

players/templates/player/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-8">
            <div class="card">
                <div class="card-header">
                    {{ player.name }}
                    <p class="float-md-right">
                        <a href="{% url 'player:player_chests' player.tag %}">Up Coming Chests</a>
                        <a href="{% url 'player:player_battles' player.tag %}">Battle Log</a>
                    </p>
                </div>
                <div class="card-body">
                    <div>
                        <table class="table table-borderless">
                            <tr>
                                <th>ExpLevel:</th>
                                <td>{{ player.expLevel }}</td>
                                <th>Arena:</th>
                                <td>{{ player.arena.name }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        <table class="table table-borderless">
                            <caption style="caption-side: top">Ladder</caption>
                            <tr>
                                <th>Trophies:</th>
                                <td>{{ player.trophies }}</td>
                                <th>Best Trophies:</th>
                                <td>{{ player.bestTrophies }}</td>
                            </tr>
                            <tr>
                                <th>Wins:</th>
                                <td>{{ player.wins }}</td>
                                <th>Losses:</th>
                                <td>{{ player.losses }}</td>
                            </tr>
                            <tr>
                                <th>Battle Count:</th>
                                <td>{{ player.battleCount }}</td>
                                <th>Three Crown Wins:</th>
                                <td>{{ player.threeCrownWins }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        <table class="table table-borderless">
                            <caption style="caption-side: top">Challenge</caption>
                            <tr>
                                <th>Challenge Cards Won:</th>
                                <td>{{ player.challengeCardsWon }}</td>
                                <th>Challenge Max Wins:</th>
                                <td>{{ player.challengeMaxWins }}</td>
                            </tr>
                            <tr>
                                <th>Tournament Cards Won:</th>
                                <td>{{ player.tournamentCardsWon }}</td>
                                <th>Tournament Battle Count:</th>
                                <td>{{ player.tournamentBattleCount }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        <table class="table table-borderless">
                            <caption style="caption-side: top">Clan: {{ player.clan.name }} <span style="margin-left: 10px">[ {{ player.role }} ]</span></caption>
                            <tr>
                                <th>Donations:</th>
                                <td>{{ player.donations }}</td>
                                <th>Donations Received:</th>
                                <td>{{ player.donationsReceived }}</td>
                            </tr>
                            <tr>
                                <th>Total Donations:</th>
                                <td>{{ player.totalDonations }}</td>
                                <th>War Wins:</th>
                                <td>{{ player.warDayWins }}</td>
                            </tr>
                            <tr>
                                <th>Clan Cards Collected:</th>
                                <td>{{ player.clanCardsCollected }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        <table class="table table-borderless">
                            <caption style="caption-side: top">League Statistics</caption>
                            <tr>
                                <th>Current Season Trophies:</th>
                                <td>{{ player.leagueStatistics.currentSeason.trophies }}</td>
                                <th>Current Season Best Trophies:</th>
                                <td>{{ player.leagueStatistics.currentSeason.bestTrophies }}</td>
                            </tr>
                            <tr>
                                <th>Previous Season Trophies:</th>
                                <td>{{ player.leagueStatistics.previousSeason.trophies }}</td>
                                <th>Previous Season Best Trophies:</th>
                                <td>{{ player.leagueStatistics.previousSeason.bestTrophies }}</td>
                            </tr>
                            <tr>
                                <th>Best Season Trophies:</th>
                                <td>{{ player.leagueStatistics.bestSeason.trophies }}</td>
                                <th>Best Season Best Trophies:</th>
                                <td>{{ player.leagueStatistics.bestSeason.bestTrophies }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        <div>
                            <span class="text-muted">Cards</span>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="card text-center">
                                        <img src="{{ player.currentFavouriteCard.iconUrls.medium }}" alt="{{ player.currentFavouriteCard.name }}" height="80px" class="rounded">
                                        <i class="text-muted" style="font-size: 13px">Current Favourite Card</i>
                                    </div>
                                </div>
                            </div>
                            <br/>
                            <div class="row no-gutters">
                                {% for item in player.cards %}
                                    <div class="col-md-1">
                                        <div class="card text-center">
                                            <img src="{{ item.iconUrls.medium }}" alt="{{ item.name }}" height="70px" class="rounded">
                                            <i class="text-muted" style="font-size: 12px">Lvl: {{ item.level }} / {{ item.maxLevel }}</i>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div>
                        <table class="table table-borderless">
                            <caption style="caption-side: top">Achievements</caption>
                            <tr>
                                <th>Name</th>
                                <th>Stars</th>
                                <th>Value</th>
                                <th>Target</th>
                                <th>Info</th>
                            </tr>
                            {% for item in player.achievements %}
                                <tr>
                                    <td>{{ item.name }}</td>
                                    <th>{{ item.stars }}</th>
                                    <td>{{ item.value }}</td>
                                    <td>{{ item.target }}</td>
                                    <td>{{ item.info }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}