api_clash/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('card/', include(('cards.urls', 'cards'), namespace='card')),
    path(
        'location/',
        include(('locations.urls', 'locations'), namespace='location')
        ),
    path('player/', include(('players.urls', 'players'), namespace='player')),
    path('clan/', include(('clans.urls', 'clans'), namespace='clan')),
]

cards/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.card_list, name='card_list'),
    path('list_with_react/', views.card_list_with_react, name='card_list'),
    path('list_with_vue/', views.card_list_with_vue, name='card_list'),
]

clans/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.clan_list, name='clan_list'),
    path('<clantag>/detail/', views.clan_detail, name='clan_detail'),
    path('<clantag>/members/', views.member_list, name='member_list'),
]

locations/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.location_list, name='location_list'),
    path(
        '<locationid>/ranking/clans/',
        views.ranking_clans,
        name='ranking_clans'
        ),
    path(
        '<locationid>/ranking/players/',
        views.ranking_players,
        name='ranking_players'
        ),
    path(
        '<locationid>/ranking/clanwars/',
        views.ranking_clanwars,
        name='ranking_clanwars'
        ),
]

templates/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock%}</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <header>
            {% block header%}
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'location:location_list' %}">Locations <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clan:clan_list' %}">Clans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'card:card_list' %}">Cards</a>
                        </li>
                    </div>
                </nav>
            {% endblock %}
        </header>
        <section class="section">
            <div class="container-fluid">
                <div class="col align-self-center">
                    {% block content %}{% endblock%}
                </div>
            </div>
        </section>
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        </script>
        <!-- react js -->
        <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
        {% block extra_js %}{% endblock %}
    </body>
    </html>