api_clash/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('card/', include(('cards.urls', 'cards'), namespace='card')),
    path(
        'location/',
        include(('locations.urls', 'locations'), namespace='location')
        ),
    path('player/', include(('players.urls', 'players'), namespace='player')),
    path('clan/', include(('clans.urls', 'clans'), namespace='clan')),
]

cards/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.card_list, name='card_list'),
    path('list_with_react/', views.card_list_with_react, name='card_list'),
    path('list_with_vue/', views.card_list_with_vue, name='card_list'),
]

clans/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('list/', views.clan_list, name='clan_list'),
    path('<clantag>/detail/', views.clan_detail, name='clan_detail'),
    path('<clantag>/members/', views.member_list, name='member_list'),
]

clans/models.py
from django.db import models

# Create your models here.

clans/views.py
import requests

from django.shortcuts import render
from django.conf import settings

from credential.views import get_headers

# Create your views here.


def clan_list(request):
    url_location = '%slocations' % settings.BASE_URL
    headers = get_headers()
    response_locations = requests.get(
        url=url_location,
        headers=headers,
        )
    locations = response_locations.json()['items']

    parameters = request.GET
    params = {}
    for k, v in parameters.items():
        if v != '':
            params.update({k: v})

    url = '%sclans' % settings.BASE_URL
    response = requests.get(
        url=url,
        headers=headers,
        params=params,
    )

    if response.status_code == 200:
        clans = response.json()['items']
    else:
        clans = {}
    return render(
        request,
        'clan/list.html',
        {'locations': locations, 'clans': clans, 'params': params}
        )


def clan_detail(request, clantag):
    import urllib.parse
    clantag = urllib.parse.quote_plus(clantag)
    url = '%sclans/%s' % (settings.BASE_URL, clantag)
    headers = get_headers()
    response = requests.get(
        url=url,
        headers=headers,
    )

    if response.status_code == 200:
        clan = response.json()
    else:
        clan = {}
    return render(request, 'clan/detail.html', {'clan': clan})


def member_list(request, clantag):
    import urllib.parse
    clantag = urllib.parse.quote_plus(clantag)
    url = '%sclans/%s/members' % (settings.BASE_URL, clantag)
    headers = get_headers()
    response = requests.get(
        url=url,
        headers=headers,
    )

    if response.status_code == 200:
        members = response.json()['items']
    else:
        members = {}
    return render(request, 'member/list.html', {'members': members})

clans/templates/clan/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-8">
            <div class="card">
                <div class="card-header">
                    {{ clan.name }}
                </div>
                <div class="card-body">
                    <div>
                        <table class="table table-borderless">
                            <tr>
                                <th>Members:</th>
                                <td>{{ clan.members }}</td>
                                <th>Location:</th>
                                <td>{{ clan.location.name }}</td>
                            </tr>
                            <tr>
                                <th>Score:</th>
                                <td>{{ clan.clanScore }}</td>
                                <th>Required Trophies:</th>
                                <td>{{ clan.requiredTrophies }}</td>
                            </tr>
                        </table>
                    </div>
                    <hr/>
                    <div>
                        {{ clan.description }}
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'clan:member_list' clan.tag %}">Members</a>
                    <a href="#">Warlog</a>
                    <a href="#">Current War</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

clans/templates/clan/list.html
{% extends 'base.html' %}

{% block content %}
    <form class="form-inline">
        <div class="form-group">
            <label>Name:</label>
            <input type="text" class="form-control my-2 mr-sm-2" name="name" value="{{params.name}}">
        </div>
        <div class="form-group">
            <label class="my-1 mr-2">Location:</label>
            <select class="custom-select my-2 mr-sm-2" name="locationId">
                {% for location in locations %}
                    <option value="{{ location.id }}" {% if params.locationId == location.id|safe %} selected {% endif %}>{{ location.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label>Min Members:</label>
            <input type="number" class="form-control my-2 mr-sm-2" style="width:80px" max="50" min="1" name="minMembers" value="{{ params.minMembers }}">
        </div>
        <div class="form-group">
            <label>Max Members:</label>
            <input type="number" class="form-control my-2 mr-sm-2" style="width:80px" max="50" min="1" name="maxMembers" value="{{ params.maxMembers }}">
        </div>
        <div class="form-group">
            <label>Min Score:</label>
            <input type="number" class="form-control my-2 mr-sm-2" style="width:100px" min="0" name="minScore" value="{{ params.minScore }}">
        </div>
        <div class="form-group">
            <label>Limit:</label>
            <input type="number" class="form-control my-2 mr-sm-2" style="width:80px" name="limit" value="{{ params.limit }}">
        </div>
        <button type="submit" class="btn btn-primary my-2">Submit</button>
    </form>
    <hr/>
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10">
            <table class="table table-light table-sm table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>Name</th>
                        <th>Score</th>
                        <th>Members</th>
                        <th>Required Trophies</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for item in clans %}
                    <tr>
                        <th>{{ item.name }}</th>
                        <td>{{ item.clanScore }}</td>
                        <td>{{ item.members }}</td>
                        <td>{{ item.requiredTrophies }}</td>
                        <td>
                            <a href="{% url 'clans:clan_detail' item.tag %}">Detail</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}